name = "RSTML"
grammar = "rstml"
autoclose_before = ">})"
block_comment = ["<!-- ", " -->"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "<", end = ">", close = false, newline = true, not_in = [
        "comment",
        "string",
    ] },
    { start = "!--", end = " --", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]
completion_query_characters = ["-"]
prettier_parser_name = "html"

[jsx_tag_auto_close]
open_tag_node_name = "open_tag"
close_tag_node_name = "close_tag"
jsx_element_node_name = "element_node"
tag_name_node_name = "node_identifier"
